CREATE TABLE IF NOT EXISTS Sensor_sample(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Measurement_sample(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id int NOT NULL REFERENCES Sensor_sample(id) ON DELETE CASCADE,
    value real NOT NULL CHECK (value >= -100 AND value <= 100 ),
    raining boolean NOT NULL,
    time timestamp NOT NULL
);

delete from sensor;
delete from measurement;
delete from sensor_sample;
delete from measurement_sample;

alter sequence sensor_id_seq restart with 1;
alter sequence measurement_id_seq restart with 1;
alter sequence sensor_sample_id_seq restart with 1;
alter sequence measurement_sample_id_seq restart with 1;

insert into sensor(name) values ('Test sensor1');
insert into sensor(name) values ('Test sensor2');
insert into sensor(name) values ('Test sensor3');