CREATE TABLE Measurement(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id int NOT NULL REFERENCES Sensor(id) ON DELETE CASCADE,
    value real NOT NULL CHECK (value >= -100 AND value <= 100 ),
    raining boolean NOT NULL,
    time timestamp NOT NULL
);
GO